<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sl</string>
	</array>
	<key>name</key>
	<string>CloudSlang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^flow:|^operation:</string>
			<key>name</key>
			<string>entity.name.section.cloudslang</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.yaml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yaml.cloudslang</string>
	<key>uuid</key>
	<string>9932e0ea-4ef0-4e2e-859b-2bebbd7991dd</string>
</dict>
</plist>
